### ISSUE TITLE
Hyperlink of discussion navigates to localhost

### ISSUE THREAD

**Issue by Maratyz** [sourcegraph/sourcegraph-code-discussions#6]
### Issue
After created an inline code discussion, the link from copy link or under discussion tab navigates back to `http://127.0.0.1:7080/<repo>/-/blob/behat.yml#tab=discussions&threadID=<threadID>&commentID=<commentID>` (localhost) and requires login. As a result, the user cannot reach the discussion via the hyperlink. 

* Version: sourcegraph 2.12.0 (Docker)
* Environment: AWS ECS task

**Comment by Maratyz** [comment]
Resolved after adding appURL according to https://about.sourcegraph.com/docs/config/custom-domain

**Comment by slimsag** [comment]
Sorry you ran into this! And yeah, configuring appURL is what fixes this. Not sure how we could make this more clear.

If you have any feedback or ideas about code discussions, please let us know! 😄
